#pragma once

#define WIFI_SSID "YOUR_WIFI_NAME"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define USER_LATITUDE 41.8781
#define USER_LONGITUDE -87.6298
#define SEARCH_RADIUS_NM 150.0

#define OPEN_SKY_CLIENT_ID ""
#define OPEN_SKY_CLIENT_SECRET ""

#define REFRESH_INTERVAL_MS 60000UL
#define OPEN_SKY_JSON_CAPACITY 262144
